TARGET    := uart
TYPE      := cdd
SOURCES   := raminfr.v uart_receiver.v uart_regs.v uart_rfifo.v uart_sync_flops.v uart_tfifo.v uart_top.v uart_transmitter.v uart_wb.v counter.v
TESTBENCH := uart_test.v wb_mast.v

include ../../common.mk
