TARGET              := uart
TYPE                := tjfree
SOURCES             := raminfr.v uart_receiver.v uart_regs.v uart_rfifo.v uart_sync_flops.v uart_tfifo.v uart_top.v uart_transmitter.v uart_wb.v
TESTBENCH           := uart_test.v wb_mast.v lfsr.v
DUT_TOP_MODULE      := uart_test.uart1
NUM_TESTS           := 1
START_TIME          := 0
TIME_LIMIT          := -1
TIME_RESOLUTION     := 10000
NUM_MALICIOUS_CNTRS := 0

include ../common.mk